export const UPDATE_UI = 'UPDATE_UI'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_THEME = 'SET_THEME'
export const SWITCH_THEME = 'SWITCH_THEME'
export const SWITCH_MODAL = 'SWITCH_MODAL'
export const SET_MODAL = 'SET_MODAL'
